# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
      - name: Use Node.js 18
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # pin@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run lint

  build:
    name: "Dry-run build"
    runs-on: ubuntu-latest
    needs: [ "lint" ]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
      - name: Use Node.js 18
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # pin@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run build
