# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v3
      - name: Use Node.js 18
        uses: actions/setup-node@c2ac33f2c62f978d6c944d9648125a294e56dc0b # pin@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run lint

  build:
    name: "Dry-run build"
    runs-on: ubuntu-latest
    needs: [ "lint" ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v3
      - name: Use Node.js 18
        uses: actions/setup-node@c2ac33f2c62f978d6c944d9648125a294e56dc0b # pin@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run build
