# This workflow is run on a push on branch main
#

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: bot-production
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v3

      - name: Use Node.JS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install npm build dependencies
        run: npm ci

      - name: Build the bot application
        run: npm run build

      - name: Remove unnecessary files for deployment
        run: |
          rm -rf ./src ./node_modules ./tsconfig.json ./.env.preset ./.git ./.github ./logs ./database.sqlite

      - name: Deploy files to production server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{secrets.PRODUCTION_DEPLOY_SSH_HOST}}
          port: ${{secrets.PRODUCTION_DEPLOY_SSH_PORT}}
          username: ${{secrets.PRODUCTION_DEPLOY_SSH_USERNAME}}
          ssh_private_key: ${{secrets.PRODUCTION_DEPLOY_SSH_KEY}}
          local_path: './'
          remote_path: ${{secrets.PRODUCTION_DEPLOY_SSH_REMOTE_PATH}}
          sftpArgs: '-o ConnectTimeout=5'
          sftp_only: true

      - name: Restart the production bot instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.PRODUCTION_DEPLOY_SSH_HOST}}
          port: ${{secrets.PRODUCTION_DEPLOY_SSH_PORT}}
          username: ${{secrets.PRODUCTION_DEPLOY_SSH_USERNAME}}
          key: ${{secrets.PRODUCTION_DEPLOY_SSH_KEY}}
          script: |
            cd ${{secrets.PRODUCTION_DEPLOY_SSH_REMOTE_PATH}}
            npm ci --omit=dev
            pm2 restart ./ecosystem.config.js --env production
